version: "3"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: "timescaledb-driftage"
    environment:
      - POSTGRES_DB=driftage_kb
      - POSTGRES_USER=agents
      - POSTGRES_PASSWORD=passw0rd
    volumes:
      - "/tmp/timescaledb:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  ejabberd:
    build: ../ejabberd_config/
    container_name: "ejabberd-driftage"
    ports:
      - 5222:5222
      - 5443:5443
  monitor:
    build: monitor/
    container_name: "spark-monitor-driftage"
    environment:
      - MONITOR_PASSWORD=passw0rd
    depends_on:
      - ejabberd
    network_mode: "host"
  analyser:
    build: analyser/
    container_name: "adwin-analyser-driftage"
    environment:
      - ANALYSER_PASSWORD=passw0rd
      - KB_CONNECTION_STRING=postgres://agents:passw0rd@localhost:5432/driftage_kb
    depends_on:
      - ejabberd
      - monitor
      - timescaledb
    network_mode: "host"
  planner:
    build: planner/
    container_name: "voting-planner-driftage"
    environment:
      - PLANNER_PASSWORD=passw0rd
      - KB_CONNECTION_STRING=postgres://agents:passw0rd@localhost:5432/driftage_kb
    depends_on:
      - ejabberd
      - executor
      - timescaledb
    network_mode: "host"
  executor:
    build: executor/
    container_name: "csv-executor-driftage"
    environment:
      - EXECUTOR_PASSWORD=passw0rd
    volumes:
      - "/tmp/executor:/tmp"
    depends_on:
      - ejabberd
    network_mode: "host"
