dist: xenial
language: python
python:
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - make setup
  - pip install coveralls  # for coveralls
# command to run tests
script:
  - sleep 5 # wait server to start
  - sudo ejabberdctl register monitor localhost passw0rd
  - sudo ejabberdctl register analyser localhost passw0rd
  - sudo ejabberdctl register planner localhost passw0rd
  - sudo ejabberdctl register executor localhost passw0rd
  - sleep 5 # wait server to configure
  - make all-tests

before_deploy: sed -i "s/version = \".*\"/version = \"$TRAVIS_TAG\"/g" setup.py

deploy:
  provider: pypi
  username: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_existing: true
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.7"

after_success: coveralls

addons:
  apt:
    packages:
    - ejabberd