version: "3"
services:
  ejabberd:
    build: ../ejabberd_config/
    container_name: "ejabberd-driftage"
    ports:
      - 5222:5222
      - 5443:5443
  monitor:
    build: monitor/
    container_name: "spark-monitor-driftage"
    environment:
      - MONITOR_PASSWORD=passw0rd
    depends_on:
      - ejabberd
    network_mode: "host"
  analyser:
    build: analyser/
    container_name: "adwin-analyser-driftage"
    environment:
      - ANALYSER_PASSWORD=passw0rd
      - KB_CONNECTION_STRING=sqlite://
    depends_on:
      - ejabberd
      - monitor
    network_mode: "host"
